on:
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v5
        id: readbody
        with:
          script: |
            const result = await github.request(context.payload.pull_request.issue_url)
            console.log(result.data.body)
            

      #- name: Get result
      #  run: echo "${{steps.readbody.body}}"
