on:
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v5
        id: readbody
        with:
          script: |
            const comments = await github.rest.issues.listComments({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
            }).then(({data}) => data)
            return comments.some(({body}) => body === "/ignore pr-size")
      - run: |
          echo "${{ steps.ignore.outputs.result}}"
            

      - name: Get result
        run: echo "${{steps.readbody.result.data.body}}"
