on:
  pull_request:
    branches: [main]
    types: [opened, synchronize]
  issue_comment:
    types: [created]    

jobs:
  comment:
    runs-on: ubuntu-latest
    steps: 
      - name: get-comment
        uses: actions/github-script@v5
        id: readbody
        with:
          script: |
            const result = await github.request(context.payload.pull_request.issue_url)
            console.log(result.data.body)
            return (result.data.body)
          result-encoding: string   
          
      - name: Conditionally Run
        if: contains(steps.readbody.outputs.result, 'username')
        run: |
          echo "SomeString did exist and should run"
      
      - name: Get result
        run: echo "${{steps.readbody.outputs.result}}"
      - name: aws auth
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-1
      - name: send message to sqs
        uses: isbang/sqs-action@v0.1.1
        with:
          sqs-url: https://sqs.us-west-1.amazonaws.com/141231375059/sqslambda
          message: "message: ${{steps.readbody.outputs.result}}"
