on:
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v5
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            // Get the existing comments.
            const {data: comments} = await github.rest.issues.listComments({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.payload.number,
              body: context.payload.pull_request.issue_url
            })
            console.log(comments.body)
      - name: View context attributes
        uses: actions/github-script@v5
        with:
         script: console.log(context)

