name: accessRequest

on:
  pull_request:
    branches: [main]
    types: [opened, synchronize,edited,closed]
    paths:
      - 'access_request/accessRequest/**'    

jobs:
  build:
    runs-on: ubuntu-latest  
    steps:  
    - name: Get startTime
      id: access
      run: |  
        export GITHUB_CONTEXT=`jq -rRn --arg GITHUB_CONTEXT ${{github.event.pull_request.merged_at}} '$GITHUB_CONTEXT | fromdate'`
    - name: Set env
      run: echo $GITHUB_CONTEXT        
    - name: Echo access.json   
      run: echo "${{ steps.access.outputs.content }}" 
    - name: Echo access.json   
      run: echo "${{ steps.access.GITHUB_CONTEXT }}" 
