on:
  pull_request:
    branches: [main]
    types: [opened, synchronize,edited,closed]
    
jobs:
  changedfiles:
    runs-on: ubuntu-latest
    # Map a step output to a job output
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - run: echo "CHANGED_FILES=$(git diff --name-only ${{ github.event.before }}" >> $GITHUB_ENV
