on:
  pull_request:
    branches: [main]
    types: [opened, synchronize,edited,closed]  
jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        if: |
            github.event.pull_request.merged == true      
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          echo "$GITHUB_CONTEXT"
