name: CI

on:
  pull_request:
    branches: [main]
    types: [opened, synchronize,edited,closed]
    #paths:
    #  - 'access_request/accessRequest/**'      

jobs:
  build:
    runs-on: ubuntu-latest  # windows-latest | macos-latest
    name: Test changed-files
    steps:
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github.event.pull_request.merged_at) }}
      run: |
        echo "$GITHUB_CONTEXT"
    - name: startTime in seconds 
      run: |
        jq -Rn '"$GITHUB_CONTEXT" | fromdate'   
