on:
  pull_request:
    branches: [main]
    types: [opened, synchronize,edited,closed]
    
jobs:
  changedfiles:
    runs-on: ubuntu-latest
    # Map a step output to a job output
    steps:
      - uses: actions/checkout@v2
      - name: changed file
        run: git diff-tree --no-commit-id --name-only -r ${{ github.sha }}
