name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest  # windows-latest | macos-latest
    name: Test changed-files
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0  # OR "2" -> To retrieve the preceding commit.

        
      - name: Get specific changed files
        id: changed-files-specific
        uses: tj-actions/changed-files@v17.2
        with:
          files: |
            **/*.json
      - name: List all changed files
        run: |
          echo ${{ steps.changed-files-specific.outputs.all_changed_files }}
