on:
  pull_request:
    branches: [main]
    types: [opened, synchronize,edited,closed]
    
jobs:
  changedfiles:
    runs-on: ubuntu-latest
    # Map a step output to a job output
    steps:

      - name: changed file
        run: |
          current_commit=`git log -n 1 --pretty=format:%H`
          echo $current_commit
