#######

name: CI

on:
  pull_request:
    branches: [new]
    #types: [opened, synchronize, edited, reopened, closed]
jobs:
  build:
    runs-on: ubuntu-latest
    name: Test changed-files
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 
      - uses: actions/checkout@v2
        with:          
          ref: new
      - name: Get specific changed files
        id: changed-files
        uses: tj-actions/changed-files@v17.2
        with:
           files: |
            **/*.json
           base_sha: ${{ github.event.pull_request.base.sha }}
           
      - name: List all added files

        run: |
          echo  ${{ toJSON(steps.changed-files.outputs.all_changed_files) }}

      - name: validate access.json file
 
        run: |
          cat  ${{ toJSON(steps.changed-files.outputs.all_changed_files) }}|jq

      - name: ls -r
        run: ls -R
      - name: Read access.json      

        id: readAccessFile
        uses: juliangruber/read-file-action@v1
        if: |
          github.event.pull_request.merged == true        
        with:
          path: ${{ toJSON(steps.changed-files.outputs.all_changed_files) }}
