name: CI

on:
  pull_request:
    branches: [main]
    types: [opened, synchronize,edited,closed]
    paths:
      - 'access_request/accessRequest/**'      

jobs:
  build:
    runs-on: ubuntu-latest 
    name: Test changed-files
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0  
      - name: List all added files
        if: |
            github.event.pull_request.merged == true      
        run: |
          for file in ${{ steps.changed-files.outputs.added_files }}; do
            echo "$file was added"
          done
