on:
  pull_request:
    branches: [main]
    types: [opened, synchronize,edited,closed]
  push:
    branches: [main]    
jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          echo "$GITHUB_CONTEXT"
