name: CI

on:
  pull_request:
    branches: [main]
    types: [opened, synchronize, edited, closed]
jobs:
  build:
    runs-on: ubuntu-latest
    name: Test changed-files
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: gitrepo 
        run: echo ${GITHUB_REPOSITORY}
      - name: Files changed after PR merge
        id: changes
        run: echo $(curl -s -X GET -G https://api.github.com/repos/${GITHUB_REPOSITORY}/pulls/${{ github.event.pull_request.number }}/files)         
     
      - name: List all added files
        run: |
          echo ${{ steps.changes.outputs.changedFile }}
