name: accessRequest

on:
  pull_request:
    branches: [main]
    types: [opened, synchronize,edited,closed]
    paths:
      - 'access_request/accessRequest/**'    

jobs:
  build:
    runs-on: ubuntu-latest  # windows-latest | macos-latest
    steps:
    - name: Get startTime
      run: |
         export GITHUB_CONTEXT=`jq -rRn --arg GITHUB_CONTEXT ${{github.event.pull_request.merged_at}} '$GITHUB_CONTEXT | fromdate'`
         echo "::set-env name=GITHUB_CONTEXT::$GITHUB_CONTEXT"
    - name: echo startTime
      run: |
         echo $GITHUB_CONTEXT
