name: CI

on:
  pull_request:
    branches: [main]
    types: [opened, synchronize,edited,closed]
    paths:
      - 'access_request/accessRequest/**'      

jobs:
  build:
    runs-on: ubuntu-latest 
    name: Test changed-files
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0  
          
      - name: Files changed after PR merge
        id: changes
        run: echo ::set-output name=docker_tag::$(curl -s -X GET -G https://api.github.com/repos/${GITHUB_REPOSITORY}/pulls/${{ github.event.pull_request.number }}/files | jq -r '.[] | .filename')
      - name: List all added files
        run: |
        
            echo ${{ steps.changes.outputs.docker_tag }}       

      - name: Get startTime
        id: access
        run: |  
          export GITHUB_CONTEXT=`jq -rRn --arg GITHUB_CONTEXT ${{github.event.pull_request.merged_at}} '$GITHUB_CONTEXT | fromdate'`
          echo $GITHUB_CONTEXT
      
            
