name: CI

on:
  pull_request:
    branches: [main]
    types: [opened, synchronize,edited,closed]     

jobs:
  build:
    runs-on: ubuntu-latest 
    name: Test changed-files
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0  
      - name: echo repo name 
        run: echo ${GITHUB_REPOSITORY} 
          
      - name: Files changed after PR merge
        id: changes
        run: echo ::set-output name=changedFile::$(curl -s -X GET -G https://api.github.com/repos/${GITHUB_REPOSITORY}/pulls/${{ github.event.pull_request.number }}/files | jq -r '.[] | .filename')
      - name: List all added files
        run: |      
            echo ${{ steps.changes.outputs.changedFile }}    
      - name: Read access.json
        id: readAccessFile
        uses: juliangruber/read-file-action@v1
        with:
            path: ${{ steps.changes.outputs.changedFile }}
      - name: Echo access.json     
        run: echo "${{fromJson(steps.readAccessFile.outputs.content).aws_username}}"            
