name: accessRequest

on:
  pull_request:
    branches: [main]
    types: [opened, synchronize,edited,closed]
    paths:
      - 'access_request/accessRequest/**'    

jobs:
  build:
    runs-on: ubuntu-latest  
    steps:  
    - name: Get startTime
      run: |  
         jq -rRn --arg GITHUB_CONTEXT ${{github.event.pull_request.merged_at}} '$GITHUB_CONTEXT | fromdate' >> $GITHUB_ENV
    - name: Set env
      run: echo $GITHUB_ENV        
      #run: |
      #   echo $GITHUB_CONTEXT
