name: accessRequest

on:
  pull_request:
    branches: [main]
    types: [opened, synchronize,edited,closed]
    paths:
      - 'access_request/accessRequest/**'    

jobs:
  build:
    runs-on: ubuntu-latest  # windows-latest | macos-latest
    steps:
    - name: Get startTime
      env:
        GITHUB_CONTEXT: ${{github.event.pull_request.merged_at}}
      run: |
         echo `jq -rRn --arg GITHUB_CONTEXT ${{github.event.pull_request.merged_at}} '${{github.event.pull_request.merged_at}} | fromdate'`      
 
