on:
  pull_request:
    branches: [main]
    types: [opened, synchronize,edited,closed]
jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0 

      - name: Read access.json
        id: access
        uses: juliangruber/read-file-action@v1
        with:
            path: ./access.json
      - name: Echo access.json
        run: echo "${{ steps.access.outputs.content }}"    
        
      - name: ConfigureAws  
        if: |
            github.event.pull_request.merged == true
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-1
        
      - name: send message 
        if: |
            github.event.pull_request.merged == true
        uses: isbang/sqs-action@v0.1.1
        with:
          sqs-url: https://sqs.us-west-1.amazonaws.com/141231375059/sqslambda
          message: "AwsUserName: ${{steps.access.outputs.content}}, starttime: ${{ github.event.commits[1].timestamp }}"
