name: accessRequest

on:
  pull_request:
    branches: [main]
    types: [opened, synchronize,edited,closed]
    paths:
      - 'access_request/accessRequest/**'    

jobs:
  build:
    runs-on: ubuntu-latest  
    
    steps:  
    - name: Get startTime
      id: access
      run: |  
        export GITHUB_CONTEXT=`jq -rRn --arg GITHUB_CONTEXT ${{github.event.pull_request.merged_at}} '$GITHUB_CONTEXT | fromdate'`
        echo $GITHUB_CONTEXT
