name: CI

on:
  push:
    branches: [new]
  pull_request:
    branches: [new]
    types: [opened, synchronize, edited, reopened]
jobs:
  build:
    runs-on: ubuntu-latest
    name: Test changed-files
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Get changed files
        id: changes
        uses: tj-actions/changed-files@v17.2

      - name: Get specific changed files
        id: changed-files-specific
        uses: tj-actions/changed-files@v17.2
        with:
          since_last_remote_commit: "true"
          files: |
            **/*.json
      - name: List all added files
        if: steps.changed-files-specific.outputs.only_changed == 'true'
        run: |
          echo  ${{steps.changed-files-specific.outputs.all_changed_files}}

      - name: validate access.json file
        if: steps.changed-files-specific.outputs.only_changed == 'true'      
        run: |
          cat  ${{steps.changed-files-specific.outputs.all_changed_files}}|jq
      - name: Read access.json
        if: steps.changed-files-specific.outputs.only_changed == 'true'      
        id: readAccessFile
        uses: juliangruber/read-file-action@v1
        with:
          path: ${{steps.changed-files-specific.outputs.all_changed_files}}
          
          
        
      - name: List all added files
        if: steps.changed-files-specific.outputs.only_changed == 'true' && github.event_name == 'push
        run: |
          echo  ${{steps.changed-files-specific.outputs.all_changed_files}}          
