name: CI

on:
  pull_request:
    branches: [main]
    types: [opened, synchronize,edited,closed]
    paths:
      - 'access_request/accessRequest/**'      

jobs:
  build:
    runs-on: ubuntu-latest  # windows-latest | macos-latest
    name: Test changed-files
    steps:
      - uses: actions/github-script@v5
        id: readbody
        with:
          script: |
            const result = await github.request(context.payload.pull_request.merged_at)            
            console.log(result.data.body)
            return (result.data.body)
          result-encoding: string
      - name: Get result
        run: echo "${{steps.readbody.outputs.result}}"  
