name: CI

on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    name: Test changed-files
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: ConfigureAws
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2
      - name: run npm install for s3
        run: npm install
        working-directory: awsResource/s3
      - run: pulumi login s3://my-bucket-3ef97f2/pulumi/
        working-directory: awsResource/s3
      - uses: pulumi/actions@v3
        with:
          command: preview
          stack-name: dev
          #comment-on-pr: true
          upsert: true
          refresh: true
          work-dir: awsResource/s3
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
          PULUMI_CONFIG_PASSPHRASE: ${{ secrets.PULUMI_CONFIG_PASSPHRASE }}
      - uses: pulumi/actions@v3
        with:
          command: up
          stack-name: dev
          #comment-on-pr: true
          upsert: true
          refresh: true
          work-dir: awsResource/s3
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
          PULUMI_CONFIG_PASSPHRASE: ${{ secrets.PULUMI_CONFIG_PASSPHRASE }}

      -  name: get s3 bucket name to push package
         id: pulumiStackOutput
         run: echo ::set-output name=bucketname::$(pulumi stack output -j | jq -r .bucketName)
      -  name: get s3 bucket name to push package 
         run: echo ${{ steps.pulumiStackOutput.outputs.bucketname }}
         

