name: CI

on:
  pull_request:
    branches: [main]
    types: [opened, synchronize,edited,closed]
    paths:
      - 'access_request/accessRequest/**'      

jobs:
  build:
    runs-on: ubuntu-latest 
    name: Test changed-files
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0  
          
      - name: Files changed after PR merge
        id: changes
        run: echo ::set-output name=changedFile::$(curl -s -X GET -G https://api.github.com/repos/${GITHUB_REPOSITORY}/pulls/${{ github.event.pull_request.number }}/files | jq -r '.[] | .filename')
      - name: List all added files
        run: |      
            echo ${{ steps.changes.outputs.changedFile }}       
      - name: Files changed after PR merge
        id: access
        run: echo ::set-output name=timeStamp::$(jq -rRn --arg GITHUB_CONTEXT ${{github.event.pull_request.merged_at}} '$GITHUB_CONTEXT | fromdate')
      - name: echo timestamp
        run: |      
            echo ${{ steps.access.outputs.timeStamp }}   
      - name: validate access.json file        
        run: |
         cat ${{ steps.changes.outputs.changedFile }}|jq 
      - name: Read access.json
        id: readAccessFile
        uses: juliangruber/read-file-action@v1
        with:
            path: ${{ steps.changes.outputs.changedFile }}
            
      - name: Echo access.json   
        #run: echo "${{ steps.access.outputs.content }}"   
        run: echo "${{fromJson(steps.access.outputs.content).aws_username}}"
      - name: ConfigureAws  
        if: |
            github.event.pull_request.merged == true
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-1

