on:
  pull_request:
    branches: [main]
    types: [opened, synchronize,edited,closed]
    
jobs:
  changedfiles:
    runs-on: ubuntu-latest
    # Map a step output to a job output
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: changed file
        run: |
           echo `git diff --name-only` 
           echo ${{ github.event.before }}
