name: CI

on:
  pull_request:
    branches: [main]
    types: [opened, synchronize,edited,closed]
    paths:
      - 'access_request/accessRequest/**'      

jobs:
  build:
    runs-on: ubuntu-latest 
    name: Test changed-files
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0  

      - name: Get changed files       
        id: changed-files
        uses: tj-actions/changed-files@v14.3

      - name: List all changed files         
        run: |
         cat ${{ steps.changed-files.outputs.all_changed_files }}|jq
      - name: Read access.json
        id: access
        uses: juliangruber/read-file-action@v1
        with:
            path: ${{ steps.changed-files.outputs.all_changed_files }}
            
      - name: Echo access.json   
        #run: echo "${{ steps.access.outputs.content }}"   
        run: echo "${{fromJson(steps.access.outputs.content).aws_username}}"
      - name: ConfigureAws  
        if: |
            github.event.pull_request.merged == true
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-1

      - name: send message 
        if: |
            github.event.pull_request.merged == true
        uses: isbang/sqs-action@v0.1.1
        with:
          sqs-url: ${{ secrets.sqs_url }}
          message: "${{fromJson(steps.access.outputs.content).aws_username}}, starttime: ${{fromJson(steps.access.outputs.content).aws_username}}"
          #message: ""aws_username": "${{fromJson(steps.access.outputs.content).aws_username}}" "startTime": "${{fromJson(steps.access.outputs.content).aws_username}}""
