name: CI

on:
  pull_request:
    branches: [main]
    types: [opened, synchronize,edited,closed]
    paths:
      - 'access_request/accessRequest/**'      

jobs:
  build:
    runs-on: ubuntu-latest 
    name: Test changed-files
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0  

      - name: Get changed files       
        id: changed-files
        uses: tj-actions/changed-files@v14.3

      - name: List all changed files          
        run: |
         echo ${{ steps.changed-files.outputs.all_changed_files }}
