name: CI

on:
  push:
    branches: [new]
  pull_request:
    branches: [new]
    types: [opened, synchronize, edited, reopened, closed]
jobs:
  build:
    runs-on: ubuntu-latest
    name: Test changed-files
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Get specific changed files
        id: changed-files
        uses: tj-actions/changed-files@v17.2
        with:
           files: |
            **/*.json
           base_sha: ${{ github.event.pull_request.base.sha }}

      - name: Show output
        run: |
          echo '${{ toJSON(steps.changed-files.outputs.all_changed_files) }}'
        shell:
          bash  
