#######

name: CI

on:
  pull_request:
    branches: [main]
    types: [opened, synchronize, edited, reopened, closed]
    paths:
      - "access_request/accessRequest/**"
jobs:
  build:
    runs-on: ubuntu-latest
    name: Test changed-files
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/checkout@v2
        with:
          ref: security_poc
      - name: Get specific changed files
        id: changed-files
        uses: tj-actions/changed-files@v17.2
        with:
          files: |
            **/*.json
          base_sha: ${{ github.event.pull_request.base.sha }}

      - name: List all added files

        run: |
          echo  ${{steps.changed-files.outputs.all_changed_files}}

      - name: validate access.json file
        run: |
          cat  ${{steps.changed-files.outputs.all_changed_files}}|jq

      - name: ls -r
        run: ls -R
      - name: Read access.json

        id: readAccessFile
        uses: juliangruber/read-file-action@v1
        if: |
          github.event.pull_request.merged == true
        with:
          path: ${{steps.changed-files.outputs.all_changed_files}}
 
